name: Build and Push to ACR

on:
  push:
    branches:
      - main   # Trigger workflow only on pushes to main
  workflow_dispatch: 
jobs:
  build-and-push:
    runs-on: windows-latest

    steps:
      # 1. Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Log in to Azure
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # 3. Log in to Azure Container Registry (ACR)
      - name: Azure Container Registry Login
        uses: azure/docker-login@v2
        with:
          login-server: aviregistry123.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      # 4. Build and push Docker image
      - name: Build and Push Docker image
        run: |
            docker build -t "aviregistry123.azurecr.io/$($env:IMAGE_NAME):$($env:IMAGE_TAG)" .
            docker push "aviregistry123.azurecr.io/$($env:IMAGE_NAME):$($env:IMAGE_TAG)"
        env:
            IMAGE_NAME: avidockerdotnet
            IMAGE_TAG: latest
  deploy:
    runs-on: windows-latest
    needs: build-and-push     
    steps:
      # 5. Deploy to Azure App Service
      # - name: Deploy to App Service
      #   uses: azure/webapps-container-deploy@v2
      #   with:
      #     app-name: dockerdotnetwebapp
      #     images: aviregistry123.azurecr.io/avidockerdotnet:latest
      #     registry-url: aviregistry123.azurecr.io
      #     registry-username: ${{ secrets.ACR_USERNAME }}
      #     registry-password: ${{ secrets.ACR_PASSWORD }}
      - name: Deploy to App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: dockerdotnetwebapp
          images: aviregistry123.azurecr.io/avidockerdotnet:latest
