name: .NET CICD

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x  # Ensure your project targets net9.0

    - name: Restore dependencies
      run: dotnet restore UI/UI.sln

    - name: Publish
      run: dotnet publish UI/UI.sln --configuration Release --output ./publish

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
          name: published-app
          path: ./publish


    

    
