name: .NET CICD pipeline

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Restore dependencies
      run: dotnet restore UI/UI.sln

    - name: Publish
      run: dotnet publish UI/UI.sln --configuration Release --output ./publish

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: published-app
        path: ./publish

  deploy:
    runs-on: windows-latest
    needs: build

    steps:
      - name: Download published artifacts
        uses: actions/download-artifact@v4
        with:
            name: published-app
            path: ./publish

      - name: Create PowerShell session to Azure VM
        shell: pwsh
        run: |
          # Add VM to TrustedHosts
          Set-Item WSMan:\localhost\Client\TrustedHosts -Value "${{ secrets.VM_IP }}" -Concatenate -Force
          $user = "./${{ secrets.VM_USERNAME }}"
          $pass = ConvertTo-SecureString "${{ secrets.VM_PASSWORD }}" -AsPlainText -Force
          $cred = New-Object PSCredential ($user, $pass)
          $global:session = New-PSSession -ComputerName ${{ secrets.VM_IP }} -Port 5985 -Authentication Basic -Credential $cred

      - name: Ensure target directory exists
        shell: pwsh
        run: |
          Invoke-Command -Session $session -ScriptBlock {
            if (-Not (Test-Path "C:\inetpub\wwwroot\aviapp")) {
              New-Item -Path "C:\inetpub\wwwroot\aviapp" -ItemType Directory
            }
          }

      - name: Copy files to IIS folder on VM
        shell: pwsh
        run: |
          Copy-Item -Path "./publish/*" -Destination "C:\inetpub\wwwroot\aviapp" -ToSession $session -Recurse -Force

      - name: Bind IIS to port 92
        shell: pwsh
        run: |
          Invoke-Command -Session $session -ScriptBlock {
            Import-Module WebAdministration
            if (-Not (Get-WebBinding -Name "Default Web Site" | Where-Object {$_.bindingInformation -like "*:92:*"})) {
              Remove-WebBinding -Name "Default Web Site" -Port 80 -Protocol "http"
              New-WebBinding -Name "Default Web Site" -Protocol "http" -Port 92 -IPAddress "*"
            }
            Restart-WebAppPool -Name 'DefaultAppPool'
          }

      - name: Remove remote PowerShell session
        shell: pwsh
        run: |
          Remove-PSSession -Session $session
