name: .NET CICD

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Restore dependencies
      run: dotnet restore UI/UI.sln

    - name: Publish
      run: dotnet publish UI/UI.sln --configuration Release --output ./publish

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: published-app
        path: ./publish

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Download published app
      uses: actions/download-artifact@v4
      with:
        name: published-app
        path: ./publish

    - name: Copy published files to Azure VM IIS folder via WinRM
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.VM_IP }}
        username: ${{ secrets.VM_USERNAME }}
        password: ${{ secrets.VM_PASSWORD }}
        port: 5985
        source: './publish/*'
        target: '${{ secrets.IIS_SITE_PATH }}'

    - name: Restart IIS on Azure VM
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VM_IP }}
        username: ${{ secrets.VM_USERNAME }}
        password: ${{ secrets.VM_PASSWORD }}
        port: 5985
        script: |
          iisreset
